//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BikeInsurance.Models
{
    using System;
    using System.Collections.Generic;
    //http://localhost:53673/Models/tblCCHP.cs
    public partial class tblCCHP
    {
        public int CCHPId { get; set; }
        public int LT100_Claim { get; set; }
        public int LT100_Unclaim { get; set; }
        public int LT125_Claim { get; set; }
        public int LT125_Unclaim { get; set; }
        public int LT150_Claim { get; set; }
        public int LT150_Unclaim { get; set; }
        public int LT200_Claim { get; set; }
        public int LT200_Unclaim { get; set; }
    }
}
