//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BikeInsurance.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCompanyName
    {
        public int CNid { get; set; }
        public int Yamaha_Claim { get; set; }
        public int Yamaha_Unclaim { get; set; }
        public int RoyalEnfield_Claim { get; set; }
        public int RoyalEnfield_Unclaim { get; set; }
        public int Honda_Claim { get; set; }
        public int Honda_Unclaim { get; set; }
        public int Hero_Claim { get; set; }
        public int Hero_Unclaim { get; set; }
        public int HeroHonda_Claim { get; set; }
        public int HeroHonda_Unclaim { get; set; }
        public int Bajaj_Claim { get; set; }
        public int Bajaj_Unclaim { get; set; }
        public int TVS_Claim { get; set; }
        public int TVS_Unclaim { get; set; }
        public int Suzuki_Claim { get; set; }
        public int Suzuki_Unclaim { get; set; }
        public int Mahindra_Claim { get; set; }
        public int Mahinda_Unclaim { get; set; }
        public int KTM_Claim { get; set; }
        public int KTM_Unclaim { get; set; }
    }
}
