//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BikeInsurance.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLoteNo
    {
        public int LotNoId { get; set; }
        public int LT10_Claim { get; set; }
        public int LT10_Unclaim { get; set; }
        public int LT20_Claim { get; set; }
        public int LT20_Unclaim { get; set; }
        public int LT30_Claim { get; set; }
        public int LT30_Unclaim { get; set; }
        public int LT40_Claim { get; set; }
        public int LT40_Unclaim { get; set; }
        public int LT50_Claim { get; set; }
        public int LT50_Unclaim { get; set; }
        public int LT60_Claim { get; set; }
        public int LT60_Unclaim { get; set; }
        public int LT70_Claim { get; set; }
        public int LT70_Unclaim { get; set; }
        public int LT80_Claim { get; set; }
        public int LT80_Unclaim { get; set; }
        public int LT100_Claim { get; set; }
        public int LT100_Unclaim { get; set; }
    }
}
