//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BikeInsurance.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTypeCover
    {
        public int TCid { get; set; }
        public int CM_Claim { get; set; }
        public int CM_Unclaim { get; set; }
        public int TP_Claim { get; set; }
        public int TP_Unclaim { get; set; }
    }
}
