//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BikeInsurance.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUserData
    {
        public int UserId { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public System.DateTime DOB { get; set; }
        public string CompanyName { get; set; }
        public int YearManufacture { get; set; }
        public decimal CCHP { get; set; }
        public int LoteNo { get; set; }
        public string Zone { get; set; }
        public string ClaimType { get; set; }
        public string Result { get; set; }
    }
}
