//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BikeInsurance.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblYM
    {
        public int YMid { get; set; }
        public int LT2010_Claim { get; set; }
        public int LT2010_Unclaim { get; set; }
        public int LT2015_Claim { get; set; }
        public int LT2015_Unclaim { get; set; }
        public int LT2020_Claim { get; set; }
        public int LT2020_Unclaim { get; set; }
    }
}
