//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BikeInsurance.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblZone
    {
        public int ZoneCountId { get; set; }
        public int ME_Claim { get; set; }
        public int ME_Unclaim { get; set; }
        public int KO_Claim { get; set; }
        public int KO_Unclaim { get; set; }
        public int SA_Claim { get; set; }
        public int SA_Unclaim { get; set; }
        public int JA_Claim { get; set; }
        public int JA_Unclaim { get; set; }
        public int BA_Claim { get; set; }
        public int BA_Unclaim { get; set; }
        public int NA_Claim { get; set; }
        public int NA_Unclaim { get; set; }
        public int GA_Claim { get; set; }
        public int GA_Unclaim { get; set; }
        public int LU_Claim { get; set; }
        public int LU_Unclaim { get; set; }
        public int DH_Claim { get; set; }
        public int DH_Unclaim { get; set; }
        public int RA_Claim { get; set; }
        public int RA_Unclaim { get; set; }
        public int BHE_Claim { get; set; }
        public int BHE_Unclaim { get; set; }
        public int KA_Claim { get; set; }
        public int KA_Unclaim { get; set; }
        public int SE_Claim { get; set; }
        public int SE_Unclaim { get; set; }
        public int MA_Claim { get; set; }
        public int MA_Unclaim { get; set; }
    }
}
